# Config file for iProtector by LDX;

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?
  God: false

  # Keep players from editing the world?
  Edit: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false

# Settings for unprotected areas in individual worlds:
Worlds:

  Braveland1:

    # Keep players from getting hurt?
    God: false

    # Keep players from editing the world?
    Edit: true

    # Protect against TNT and Creeper explosions?
    TNT: true

    # Keep players from touching blocks and activating things like chests?
    Touch: false

  world:

    # Keep players from getting hurt?
    God: true

    # Keep players from editing the world?
    Edit: true

    # Protect against TNT and Creeper explosions?
    TNT: true

    # Keep players from touching blocks and activating things like chests?
    Touch: false

  blank:

    # Keep players from getting hurt?
    God: true

    # Keep players from editing the world?
    Edit: true

    # Protect against TNT and Creeper explosions?
    TNT: true

    # Keep players from touching blocks and activating things like chests?
    Touch: false

