#Configuration file for BigBrother plugin

#Do not change the interface if you don't know what you are doing. It's good as it is now
interface: 149.202.92.161
port: 41754

network-compression-threshold: 256

#Sets the server description on the server list
motd: "§bPocketMine-MP server using §6§lBigBrother§r§b plugin\n§aConnect to Minecraft: PE Braveland for PC clients"

#Use Mojang services to authenticate players
online-mode: true

#This is Skin Settings
skin-yml: "steve.yml"
skin-slim: false
